### PR TITLE
Adding SMP Support

### PR DESCRIPTION
**Pull request by tuxfan**
- Adds configuration file for `smp`.

### CODE REVIEW

**Comment by bonachea** [comment]
I have a comment/question for @elliottslaughter @streichler which applies to all of these config files (including the one being added here).

Some of the configure options reflected in these files are obsolescent, in some cases for over 5 years now.      
**What is the oldest version of GASNet that Realm (and more specifically repo) are trying to support?** 

I see the repo currently contains GASNet versions dating back to GASNet-1.30.0.tar.gz which was released in 2017, are you actually trying to support running with 6-year old GASNet? If so, why? 

FWIW our general GASNet support policy is to support EX releases up to 2 years in age, and GASNet-1 release packages are no longer supported at all (the GASNet-1 API remains supported in EX). We always strongly encourage use of the latest release of GASNet-EX (absent a good reason, such as tracking a regression or attempting to run on EOL hardware). 

CC: @phhargrove

**Comment by elliottslaughter** [comment]
In my [thread on this topic](https://legion.zulipchat.com/#narrow/stream/187787-general/topic/oldest.20gasnet.20in.20active.20use) users reported using GASNet 1.32.0 (actively, for Quartz at LLNL) and 2021.3.0 (this was for a paper, so no longer active use, but possibly of interest for improving or replicating results).

We have no formal deprecation policy but I was going to prune versions older than that, and if there's some newer target we should be aspiring to, it would be good to let us know. Most of our users probably take the default, which we pin to (usually) the newest version, typically within a couple months from release. E.g., right now it's 2022.9.2.

**Comment by elliottslaughter** [comment]
If we take (say) 1.32.0 and 2021.3.0 as a floor (for now), what options could we prune?

**Comment by elliottslaughter** [comment]
For what it's worth, I did the removals suggested above. If you think it's appropriate to do more, let us know.

**Comment by bonachea** [comment]
@elliottslaughter said:
> using GASNet 1.32.0 (actively, for Quartz at LLNL) 

IIUC from public documentation LLNL Quartz is Omni-Path, which is directly supported by GASNet-EX starting in version 2022.3.0. So I'd highly recommend re-evaluating this use case, as they probably can/should upgrade to the latest GASNet-EX.

One caveat is that Cornelis (who now owns the Omni-Path IP) is actively developing a [new OPX provider](https://www.openfabrics.org/wp-content/uploads/2022-workshop/2022-workshop-presentations/106_TThompson.pdf), which AFAIK is not yet supported by ANY version of GASNet (due to missing provider capabilities and related defects). So if Quartz is running the Cornelis driver they might be unable to run any version of GASNet ofi-conduit (yet), although we have an active dialog with Cornelis to close this gap.

> 2021.3.0 (this was for a paper, so no longer active use, but possibly of interest for improving or replicating results).

I agree that reproducing old published results is a worthwhile use case. However I'd respectfully submit that such a use case should probably use old versions of the ENTIRE software stack (including the then-current version of this repo). IOW git never forgets, and if you tag the version of this repo that was current for 2021.3.0, then using that tag is probably the most reliable way to reproduce results.

**Comment by bonachea** [comment]
> If we take (say) 1.32.0 and 2021.3.0 as a floor (for now), what options could we prune?

Those two releases differ in time by 2.5 years, so the answer strongly depends on whether we can in fact drop 1.32. Once you're certain what's being kept I can provide a more accurate answer.

**Comment by elliottslaughter** [comment]
Thanks. I'll move remaining discussion of obsolete versions to a new issue.

**Comment by elliottslaughter** [comment]
@bonachea Do you have any concerns about the content of this PR, aside from flags that we'd be able to clean up by removing older GASNet versions? (Which we can do independently of this particular PR.)

**Comment by bonachea** [comment]
@elliottslaughter no concerns about this PR in particular. Apologies for the tangential discussion, as you say we can pursue that in issue #10

**Pull request merged**
